const raw=[
['v01','Welcome to StreamBox','StreamBox','Entertainment'],['v02','Gaming Highlights','StreamBox Gaming','Gaming'],['v03','Basketball Training','StreamBox Sports','Sports'],['v04','Guitar Session','StreamBox Music','Music'],['v05','Learn JavaScript','Code Academy','Education'],['v06','Tech Setup Tour','Tech World','Tech'],['v07','Funny Moments','StreamBox','Entertainment'],['v08','Football Highlights','StreamBox Sports','Sports'],['v09','Piano Performance','StreamBox Music','Music'],['v10','HTML Basics','Code Academy','Education'],['v11','PC Building Guide','Tech World','Tech'],['v12','Gaming Challenge','StreamBox Gaming','Gaming'],['v13','Sports Skills','StreamBox Sports','Sports'],['v14','Acoustic Session','StreamBox Music','Music'],['v15','Web Design Tips','Code Academy','Education'],['v16','Best Gadgets','Tech World','Tech'],['v17','Behind the Scenes','StreamBox','Entertainment'],['v18','Soccer Skills','StreamBox Sports','Sports'],['v19','Music Theory','StreamBox Music','Music'],['v20','Coding Project','Code Academy','Education'],['v21','Study Tips','Code Academy','Education'],['v22','Science Explained','Science Lab','Education'],['v23','Movie Making','StreamBox','Entertainment'],['v24','Creative Ideas','StreamBox','Entertainment'],['v25','Drawing Tutorial','Creative Hub','Education'],['v26','Game Design','StreamBox Gaming','Gaming'],['v27','Sound Engineering','StreamBox Music','Music'],['v28','Live Performance','StreamBox Music','Music'],['v29','Build With Code','Code Academy','Tech'],['v30','StreamBox Showcase','StreamBox','Entertainment']];
const videos=raw.map((v,i)=>({file:v[0]+'.mp4',thumb:v[0]+'.jpg',title:v[1],channel:v[2],cat:v[3],time:'0:05',views:(137+i*41)+'K views',age:(i%9+1)+' days ago'}));
let current=null,likes=0;
function card(v,i){return `<article class="card" onclick="watchVideo(${i})"><div class="thumb"><img src="thumbnails/${v.thumb}" alt=""><span class="time">${v.time}</span></div><div class="info"><div class="mini">▶</div><div><div class="title">${v.title}</div><div class="meta">${v.channel}<br>${v.views} • ${v.age}</div></div></div></article>`}
function render(list=videos){document.getElementById('grid').innerHTML=list.map(v=>card(v,videos.indexOf(v))).join('')}
function watchVideo(i){current=videos[i];home.style.display='none';watch.style.display='block';videoPlayer.src='videos/'+current.file;watchTitle.textContent=current.title;channelName.textContent=current.channel;likes=0;likeCount.textContent=likes;window.scrollTo(0,0)}
function showHome(){watch.style.display='none';home.style.display='block';pageTitle.textContent='Recommended';setActive('All');render()}
function filterCategory(cat){pageTitle.textContent=cat;setActive(cat);render(videos.filter(v=>v.cat===cat))}
function searchVideos(){const q=search.value.toLowerCase().trim();pageTitle.textContent=q?`Search results for "${q}"`:'Recommended';render(q?videos.filter(v=>(v.title+' '+v.channel+' '+v.cat).toLowerCase().includes(q)):videos)}
function setActive(name){document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('selected',x.textContent===name||name==='All'&&x.textContent==='All'))}
search.addEventListener('keydown',e=>{if(e.key==='Enter')searchVideos()});
fileInput.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);videos.unshift({file:url,thumb:null,title:f.name.replace(/\.[^.]+$/,''),channel:'My Upload',cat:'Entertainment',time:'Local',views:'0 views',age:'Just now',local:true});render()});
function likeVideo(){likes++;likeCount.textContent=likes}function shareVideo(){navigator.clipboard?.writeText(location.href).then(()=>alert('Page link copied!')).catch(()=>alert('Copy the page URL to share it.'))}function saveVideo(){alert('Saved to your playlist!')}
function toggleSidebar(){sidebar.classList.toggle('collapsed')}
render();
